This notebook is part of Dr. Christoforos Christoforou's course materials. You may not, nor may you knowingly allow others to reproduce or distribute lecture notes, course materials or any of their derivatives without the instructor's express written consent.

# Problem Set 03 - Support Vector Machines Classifiers
**Professor:** Dr. Christoforos Christoforou

For this problem set you will need the following libraries, which are pre-installed with the colab environment: 

* [Numpy](https://www.numpy.org/) is an array manipulation library, used for linear algebra, Fourier transform, and random number capabilities.
* [Pandas](https://pandas.pydata.org/) is a library for data manipulation and data analysis.
* [Matplotlib](https://matplotlib.org/) is a library which generates figures and provides graphical user interface toolkit.

You can load them using the following import statement:

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

## 1. Objective 
As part of this problem set, you will expore work on the `wine quality dataset`  in order to: 
- To explore the physiocochemical properties of red wine
- To determine an optimal machine learning model for red wine quality classification

For that, you will be using an `instance-based` classifier, namely K-NN algorithm. Review the information provided in the problem set, and complete all challenges listed.  

## 2. Wine Quality Dataset - Data Description

For this dataset you will be using the `wine quality dataset`. Below is a description of the various parameters listed in that dataset (i.e. potential features):

* fixed.acidity (tartaric acid - g / dm^3): most acids involved with wine or fixed or nonvolatile (do not evaporate readily) 
* volatile.acidity (acetic acid - g / dm^3): the amount of acetic acid in wine, which at too high of levels can lead to an unpleasant, vinegar taste 
* citric.acid (g / dm^3): the amount of acetic acid in wine, which at too high of levels can lead to an unpleasant, vinegar taste 
* residual.sugar (g / dm^3): the amount of sugar remaining after fermentation stops, it's rare to find wines with less than 1 gram/liter and wines with greater than 45 grams/liter are considered sweet 
* chlorides (sodium chloride - g / dm^3): the amount of salt in the wine 
* free.sulfur.dioxide (mg / dm^3): the free form of SO2 exists in equilibrium between molecular SO2 (as a dissolved gas) and bisulfite ion; it prevents microbial growth and the oxidation of wine 
* total.sulfur.dioxide (mg / dm^3): amount of free and bound forms of S02; in low concentrations, SO2 is mostly undetectable in wine, but at free SO2 concentrations over 50 ppm, SO2 becomes evident in the nose and taste of wine 
* density (g / cm^3): the density of water is close to that of water depending on the percent alcohol and sugar content 
* pH: describes how acidic or basic a wine is on a scale from 0 (very acidic) to 14 (very basic); most wines are between 3-4 on the pH scale 
* sulphates (potassium sulphate - g / dm3): a wine additive which can contribute to sulfur dioxide gas (S02) levels, wich acts as an antimicrobial and antioxidant 
* alcohol (% by volume): the percent alcohol content of the wine 
* quality: quality score between 0 and 10



## Download dataset from kaggle
You will use the Kaggle CLI to dowload the `Wine Quality Dataset` to your colab enviroment. You will need to upload your kaggle API (see problem_set 01 for direction on how to obtain your API key. 

In [ ]:
# install kaggle CLI
!pip install -q kaggle

In [ ]:
# Upload the kaggle API key of your account 
from google.colab import files 
files.upload()
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json


In [ ]:
# View list of data files available in the dataset. 
# Format : kaggle dataset files <dataset-URI>
!kaggle datasets files cchristoforou/practice-dataset-for-tutorials

name                  size  creationDate         
-------------------  -----  -------------------  
wine.data             11KB  2021-01-23 15:26:18  
countries.csv          2KB  2021-01-23 15:26:18  
wineQualityReds.csv   92KB  2021-01-23 15:26:18  
country_total.csv    533KB  2021-01-23 15:26:18  


In [ ]:
# Download - Specify the parameters.  
kaggle_dataset_URI = "cchristoforou/practice-dataset-for-tutorials"
output_folder = "sample_data/problem_set02"
kaggle_data_file1 = "wineQualityReds.csv"

In [ ]:
# Download the first file from dataset - countries.csv
!kaggle datasets download $kaggle_dataset_URI --file $kaggle_data_file1 --path $output_folder 


  0% 0.00/92.1k [00:00<?, ?B/s]
100% 92.1k/92.1k [00:00<00:00, 39.2MB/s]


## Load the data 
The code below showcase how to load the data in a pandas `DataFrame` and apply a train_test_split on the data. 

In [ ]:
# Code to load the data from file. Here we use the pandas library to read the csv file. 
datafile = "/content/wineQualityReds.csv"
wine_df = pd.read_csv(datafile)
wine_df.drop(wine_df.columns[0],axis=1,inplace=True)

In [ ]:
# Split the data into a training and testing set using the sklearn function train_test_split
# Noteice that 
# Split the data into a training and testing set using the sklearn function train_test_split
# Noteice that
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(wine_df.drop('quality',axis=1), wine_df['quality'], test_size=.25, random_state=42)


## Challenge 1
Use the variables `X_train`, `X_test`, `y_train`, and `y_test` to explore your data. In particular, calculate and display the following information.

* Number of samples in the training set in total and in each class.
* Number of samples in the testing set in total and in each class.
* Number of features in the dataset. 
* Number of classes in the dataset.
* IDs of the number of classes.


In [ ]:
# Your Solution here
# Your Solution here
print("x_train:", X_train.shape, ". y_train:", y_train.shape)
print("x_test:", X_test.shape, ". y_test:", y_test.shape)
print("ID: " + str(np.unique(y_test)))

x_train: (1199, 11) . y_train: (1199,)
x_test: (400, 11) . y_test: (400,)
ID: [3 4 5 6 7 8]


# Challenge 2

Train a **SVM** classifier using the `(X_train,y_train)` dataset and use the trained model to predict the underlying classes for the observations in the test dataset `X_test`. Store your prediction in a variable called `y_pred`.

In [ ]:
# Your solution 
from sklearn import svm
model = svm.SVC()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred

array([5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6,
       6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5,
       6, 5, 6, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6,
       5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 7, 6,
       6, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5,
       6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 5, 6, 5,
       6, 5, 6, 6, 6, 5, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6,
       6, 6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6,

# Challenge 3

Evaluate the performance of your classifier. Calculate and display the following:
* print the `confusion matrix`.
* `normalized confusion matrix`. 
* the probablitity of correct classification (accuracy score). 
* the `precision`, `recall`, and `f1-score` for each class.

In [ ]:
# Your solution 
matrix = metrics.confusion_matrix(y_test, y_pred)
matrix

array([[  0,   0,   0,   1,   0,   0],
       [  0,   0,   2,  11,   0,   0],
       [  0,   0,  83,  81,   0,   0],
       [  0,   0,  49, 120,   0,   0],
       [  0,   0,   5,  42,   1,   0],
       [  0,   0,   1,   4,   0,   0]])

In [ ]:
normalized_matrix = matrix.astype('float32') / matrix.sum()
normalized_matrix

array([[0.    , 0.    , 0.    , 0.0025, 0.    , 0.    ],
       [0.    , 0.    , 0.005 , 0.0275, 0.    , 0.    ],
       [0.    , 0.    , 0.2075, 0.2025, 0.    , 0.    ],
       [0.    , 0.    , 0.1225, 0.3   , 0.    , 0.    ],
       [0.    , 0.    , 0.0125, 0.105 , 0.0025, 0.    ],
       [0.    , 0.    , 0.0025, 0.01  , 0.    , 0.    ]], dtype=float32)

In [ ]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        13
           5       0.59      0.51      0.55       164
           6       0.46      0.71      0.56       169
           7       1.00      0.02      0.04        48
           8       0.00      0.00      0.00         5

    accuracy                           0.51       400
   macro avg       0.34      0.21      0.19       400
weighted avg       0.56      0.51      0.47       400



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Challenge 4

The code below loads the same dataset, but treats it as a binary classification problem. That is, instead of classifying an observation into one of 10 categories (0..10), we consider all observations with score above 5 as being good and all observation below or equal to five as being bad.





In [ ]:
# Code to load the data from file. Here we use the pandas library to read the csv file. 
datafile = "/content/wineQualityReds.csv"
wine_df = pd.read_csv(datafile)
wine_df.drop(wine_df.columns[0],axis=1,inplace=True)

wine_df['quality'] = np.where(wine_df['quality']>5,"Good","Bad")

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(wine_df.drop('quality',axis=1), wine_df['quality'], test_size=.25, random_state=42)


## Callenge 4.1
Use the variables `X_train`, `X_test`, `y_train`, and `y_test` to explore your data. In particular, calculate and display the following information.
* Number of samples in the training set in total and in each class.
* Number of samples in the testing set in total and in each class.
* Number of features in the dataset. 
* Number of classes in the dataset.
* IDs of the number of classes.




In [ ]:
# Your Solution 
# Your Solution here
# Your Solution here
print("x_train:", X_train.shape, ". y_train:", y_train.shape)
print("x_test:", X_test.shape, ". y_test:", y_test.shape)
print("ID: " + str(np.unique(y_test)))

x_train: (1199, 11) . y_train: (1199,)
x_test: (400, 11) . y_test: (400,)
ID: ['Bad' 'Good']


## Challenge 4.2 
Train a **Support Vector Machine** classifier using the `(X_train,y_train)` dataset and use trained model to predict the underlying classes for the observations in the test dataset `X_test`. Store your prediction in a variable called `y_pred`.

In [ ]:
# Your solution 
model = svm.SVC()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred


array(['Good', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 'Good', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Good',
       'Bad', 'Good', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Good', 'Good',
       'Good', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 

## Challenge 4.3
Evaluate the performance of your classifier. Calculate and display the following:
* print the `confusion matrix`.
* `normalized confusion matrix`. 
* the probablitity of correct classification (accuracy score). 
* the `precision`, `recall`, and `f1-score` for each class.

In [ ]:
# Your Solution 
matrix = metrics.confusion_matrix(y_test, y_pred)
matrix

array([[ 65, 113],
       [ 32, 190]])

In [ ]:
normalized_matrix = matrix.astype('float32') / matrix.sum()
normalized_matrix

array([[0.1625, 0.2825],
       [0.08  , 0.475 ]], dtype=float32)

In [ ]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         Bad       0.67      0.37      0.47       178
        Good       0.63      0.86      0.72       222

    accuracy                           0.64       400
   macro avg       0.65      0.61      0.60       400
weighted avg       0.65      0.64      0.61       400



# Challenge 5

The **SVM** classifier accepts a number of parameters. These parameters include the parameter `C` (i.e. the regularization parameter), the `kernel` which specified the kernel function to be used, and the parameter `gamma` which can be used to specify the kernel coefficents for certain kernels (i.e. `rbf`, `poly` and `sigmoid`). You can find more information about the various parameters in implementation of the SVM classifier on the following website:

- [SVM documentation on sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC)
- [User Guide on Support Vector Machines](https://scikit-learn.org/stable/modules/svm.html#svm-classification)
- [Kernel Function Supported by sklearn library](https://scikit-learn.org/stable/modules/svm.html#svm-kernels)


After reading the documentation to understand how the various parameters are used, evaluate the classifier for different values of C, gamma and kernel parameters and identify which configuration achieve the best performance on the testing set. Plot or print your results.


In [ ]:
# Your solution 
# Kernel = linear
# Gamma = auto
# C = 2
model = svm.SVC(kernel='linear', C=2, gamma='auto')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred


array(['Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Good',
       'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Bad',
       'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Bad', 'Good',
       'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Bad',
       'Good', 'Good', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Bad',
       'Good', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good',
       'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good',
       'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Bad', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Good', 'Good',
       'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Bad',
       'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Bad',
       'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Good',
       'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Bad', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Go

In [ ]:
matrix = metrics.confusion_matrix(y_test, y_pred)
matrix

array([[136,  42],
       [ 67, 155]])

In [ ]:
normalized_matrix = matrix.astype('float32') / matrix.sum()
normalized_matrix

array([[0.34  , 0.105 ],
       [0.1675, 0.3875]], dtype=float32)

In [ ]:
# Performed better than original verion 73 > 64
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         Bad       0.67      0.76      0.71       178
        Good       0.79      0.70      0.74       222

    accuracy                           0.73       400
   macro avg       0.73      0.73      0.73       400
weighted avg       0.73      0.73      0.73       400



In [ ]:
# Your solution 
# Kernel = linear
# Gamma = scale
# C = 1.5
model = svm.SVC(kernel='linear', C=1.5, gamma='scale')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_pred

array(['Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Good',
       'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Bad',
       'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Bad', 'Good',
       'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Bad',
       'Good', 'Good', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Bad',
       'Good', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good',
       'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good',
       'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Bad', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Good', 'Good',
       'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Good', 'Bad',
       'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Good', 'Bad',
       'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Good',
       'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Bad', 'Good', 'Good', 'Good', 'Good', 'Bad', 'Good', 'Go

In [ ]:
matrix = metrics.confusion_matrix(y_test, y_pred)
matrix

array([[135,  43],
       [ 66, 156]])

In [ ]:
normalized_matrix = matrix.astype('float32') / matrix.sum()
normalized_matrix

array([[0.3375, 0.1075],
       [0.165 , 0.39  ]], dtype=float32)

In [ ]:
# Performed similarly to previous example
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         Bad       0.67      0.76      0.71       178
        Good       0.78      0.70      0.74       222

    accuracy                           0.73       400
   macro avg       0.73      0.73      0.73       400
weighted avg       0.73      0.73      0.73       400




Copyright Statement: Copyright © 2020 Christoforou. The materials provided by the instructor of this course, including this notebook, are for the use of the students enrolled in the course. Materials are presented in an educational context for personal use and study and should not be shared, distributed, disseminated or sold in print — or digitally — outside the course without permission. You may not, nor may you knowingly allow others to reproduce or distribute lecture notes, course materials as well as any of their derivatives without the instructor's express written consent.